### ISSUE TITLE
Implement a "Not found" page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#11]
Currently if somehow the user tries to access an inexistent page on the site, we show a blank page with an error.
https://origin-website-staging.herokuapp.com/doesnotexist

We should handle these error and display a more user friendly page. See for example 
https://www.originprotocol.com/en/doesnotexit

**Comment by shahthepro** [comment]
I added a simple 404 page that only renders a "page not found" text for now but let's keep this open until we have a basic layout for that at least

**Comment by micahalcorn** [comment]
Designs in https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=2354%3A23875&t=SoRBE4EYvmBZ82C6-1 🎨
