### ISSUE TITLE
URI scheme for legacy content and localization

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#13]
### Legacy URLs
- /team -> redirect to /company
- /es/team -> redirect to /team (but ideally directly to /company)
- Note: implement as pass-thru via Next.js
   - Client requests https://www.originprotocol.com/total-ogn
   - DNS resolves to the Next.js server
   - Server gets the request
   - Server issues a request to the old Python stack at https://api.originprotocol.com/total-ogn
   - Server receives the response and sends it back to the client
   - Note: we can leverage Next.js's native URL rewrite: https://nextjs.org/docs/api-reference/next.config.js/rewrites
### New URLs
  - /company -> english version
  - /en/company -> /company
   - /\<locale\>/company -> /company (for v1 until we localize, then support localized content in v2)

## CMS pages
 - For v1
   - /article/<slug>
- For v2 (**after the launch**)
  - /article/\<locale\>/<english slug>
    - We'll have to do a lookup to get the \<locale\> article based on the english slug
   - Assuming the translated articles are tied to the original

**Comment by rolandpo** [comment]
added some redirects here https://github.com/OriginProtocol/website-frontend/blob/5eb47d6ba9383c1f7fa790b9eb8e3802d5911b17/next.config.js#L23 if that might come in handy
