### ISSUE TITLE
Google analytics 

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#14]
P0: Have tags on every pages to track the traffic to each of them.

P1 (not blocking for launch): track specific actions (for ex. click on buttons). We'll want marketing to provide a list of actions they'd like to track.

**Comment by franckc** [comment]
@micahalcorn Could you talk to marketing and give us a list of specific action we should track?

**Comment by rolandpo** [comment]
page analytics added + mailing list event tracking for now. Permissions will have to be set up when it goes to production

**Comment by nickick** [comment]
Tested that network traffic for GA is live on production
