### ISSUE TITLE
Home page: Latest Stories section is missing content

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#15]
On the homepage on staging at https://origin-website-staging.herokuapp.com/, the Latest Stories section seems to be missing content.

<img width="1052" alt="Screen Shot 2022-10-05 at 9 34 46 PM" src="https://user-images.githubusercontent.com/945910/194215093-8641d106-7d23-4e50-9d1a-9b373007e3ee.png">

**Comment by rolandpo** [comment]
added a fix for this. I might change the way we fetch those articles later but not a blocker
