### ISSUE TITLE
Invalid links on the landing page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#18]
On the landing page at https://origin-website-staging.herokuapp.com/
 - [ ] "Meet the team": currently points to https://story.xyz. It should point to the team section of the new company page at https://origin-website-staging.herokuapp.com/company
 - [ ] "View careers": As opposed to pointing to https://story.xyz it should point our jobs on angelist

**Comment by rolandpo** [comment]
fixed, 'Meet the team' points to /community, 'View careers' points to Angel List
