### ISSUE TITLE
Missing images on the community page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#19]
There are 2 images missing for Medium and Weibo under the community section of https://staging-next.originprotocol.com/community

<img width="956" alt="Screen Shot 2022-10-11 at 9 58 58 PM" src="https://user-images.githubusercontent.com/945910/195254079-d8c61687-9d2b-4e04-93b3-7acb96a3fe5a.png">

**Comment by rolandpo** [comment]
added
