### ISSUE TITLE
Reliable contributors data

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/website-frontend#48]
The GitHub contributors data often doesn't load.

![image](https://user-images.githubusercontent.com/273937/199018019-0a8f5f42-671f-44f0-821d-457fe1c731fb.png)

**Comment by rolandpo** [comment]
fix is up to at least hide the '0 open-source contributors' when not loaded, not yet deployed

**Comment by micahalcorn** [comment]
> fix is up to at least hide the '0 open-source contributors' when not loaded, not yet deployed

Thanks, what's the underlying issue here?

**Comment by rolandpo** [comment]
there's a lot of calls going on to get contributors from multiple repositories so might be going over the API limit, might have to add some access token to the request

**Comment by micahalcorn** [comment]
> there's a lot of calls going on to get contributors from multiple repositories so might be going over the API limit, might have to add some access token to the request

Would it make sense for us to just store the information in our db and then update it periodically with a cron job or something?

**Comment by joshfraser** [comment]
We already built a script to pull and cache this on the python stack. Perhaps we serve the data from the API instead?

**Comment by rolandpo** [comment]
oh yeah good call, I'll look into it in a bit

**Comment by rolandpo** [comment]
related PR:
https://github.com/OriginProtocol/origin-website/pull/651

**Comment by rolandpo** [comment]
I believe this is fixed with fddaa00f55990d533b3f0df38e19705fb1b9900b

**Comment by franckc** [comment]
marking as done. nice work @rolandpo
