### ISSUE TITLE
Press kit

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/website-frontend#49]
We need to update the graphics in the press kit to be the correct ones and include higher-resolution versions in the download. We're currently blocked on this until we can agree on which versions to use.

**Comment by micahalcorn** [comment]
Here is the final group of assets that we'll want to include in the press kit.

[Origin_Logos.zip](https://github.com/OriginProtocol/website-frontend/files/9993932/Origin_Logos.zip)

**Comment by rolandpo** [comment]
done
