### ISSUE TITLE
Article page: missing author information

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#5]
The author information does not show up at the bottom of the article page.

For ex see:
 - CMS article: https://origin-cms-staging.herokuapp.com/admin/content-manager/collectionType/api::blog.website-post/6?plugins[i18n][locale]=en
 - Associated article page: https://origin-website-staging.herokuapp.com/blog/website-post-3

**Comment by rolandpo** [comment]
author added to articles, just waiting for avatar in the response to display that too

**Comment by shahthepro** [comment]
I have updated the Strapi API to include cover as well as the author images in PR https://github.com/OriginProtocol/origin-cms/pull/8

That should unblock you @rolandpo

**Comment by nickick** [comment]
This is working now on article pages.
