### ISSUE TITLE
Social preview images

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/website-frontend#50]
When a blog page is linked from Facebook, Twitter, Discord, etc, the preview image should be populated with the primary image at the top of the blog post. Compare these two tweets; the first involves a Medium link and the second involves our blog:

<img width="586" alt="Screen Shot 2022-10-31 at 8 57 54 AM" src="https://user-images.githubusercontent.com/273937/199052809-e16c66b6-3a79-4b39-8a06-7385719b2c83.png">

**Comment by rolandpo** [comment]
this has been fixed, thanks to @nickick
