### ISSUE TITLE
Restore token dashboard

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/website-frontend#63]
<img width="761" alt="Screen Shot 2022-11-11 at 7 39 51 PM" src="https://user-images.githubusercontent.com/273937/201454661-5c7124a1-f621-4fa7-8e70-8c2d0ee96650.png">
<img width="761" alt="Screen Shot 2022-11-11 at 7 40 28 PM" src="https://user-images.githubusercontent.com/273937/201454662-99c3dcd5-17b0-4078-98d6-c0fbc5f841fb.png">

**Comment by rolandpo** [comment]
#64 adds a link to https://api.originprotocol.com/en/dashboard to the 'Buy OGN' button. Is there anything else to be done here?
