### ISSUE TITLE
Press kit cleanup

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/website-frontend#70]
Let's vertically align the text on each of these cards. Due to the varying text length, there is currently some excess space above "Origin Logo" on the first card. The headings and the descriptions should all be pinned to the top of the card while the Download links should be pinned to the bottom. Basically, we want space between instead of space before the content.

The text is also quite redundant. The headings almost exactly match the images and the text below them. Each description starts with the word "Download" and then is followed by a "Download" link. How about losing the headings entirely and then either replacing the download links with a visual icon or making the descriptions sentence fragments without the word (e.g. "The Origin Protocol logo")?

<img width="1275" alt="Screen Shot 2022-12-05 at 2 32 24 PM" src="https://user-images.githubusercontent.com/273937/205757072-0a36ecc2-1c78-42f6-b1ca-981a613c700a.png">

**Comment by matt-bullock** [comment]
Heading and description should be pinned to the top left. I noticed this on the blog posts earlier today and asked Roland to fix. Missed it here. I had the header and description in there to follow the card patterns across the rest of the site, but this can be changed. We can jump on a quick call to make those other changes and see what reads best.

**Comment by rolandpo** [comment]
title and description spacing pending here https://github.com/OriginProtocol/origin-storybook/pull/17

**Comment by micahalcorn** [comment]
I cleaned up some of the text. It's fine for now.

<img width="1263" alt="Screen Shot 2022-12-06 at 8 05 10 AM" src="https://user-images.githubusercontent.com/273937/205962311-49127ff1-74bb-469f-bd7d-aafa31728e99.png">
