### ISSUE TITLE
Prevent iFraming

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#71]
We should not allow any of our new marketing sites to get embedded as an iframe:
 - originprotocol.com
 - ousd.com
 - story.xyz

Let's disallow that by adding the proper headers:
```
X-Frame-Options: DENY
Content-Security-Policy: frame-ancestors 'none'
```

**Comment by rolandpo** [comment]
headers added for ousd.com, and for originprotocol.com in #73
