### ISSUE TITLE
Canonicalize URLs

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#72]
The originprotocol.com [google indexing issue report](https://docs.google.com/spreadsheets/d/1tOjcsmM_inZbi22a43XFXsdSCQEdU7dOrx5OGXnLOs0/edit#gid=1141042641) shows a significant numbers of URLs having duplicate content and this is impacting our SEO score.

One of the largest category is URLs with parameters. Here are a few examples:
 - https://www.originprotocol.com/?source=post_page-----51fab9d36292-----------------------------------
 - https://www.originprotocol.com/?lang_code=nl
 - https://www.originprotocol.com/ko?video_id=VzLkShX9-VE

It is unclear why google attempts to index those in the first place. Most likely there are external sites hosting those links.

We are not using URL parameters on the new site. So let's canonicalize all URLs by stripping any parameters and then redirect to the canonicalized version. For example:
 - Request for https://www.originprotocol.com/?source=post_page-----51fab9d36292----------------------------------- is made
 - Server strips the parameters and sends a 301 to https://www.originprotocol.com/

**Comment by franckc** [comment]
@rolandpo The PR is deployed to production but it does not look like everything is fixed so I'm re-opening this issue.
 - [ ] When fetching the homepage at https://www.originprotocol.com, the server does not include the  `x-frame-options: DENY` header in the response
 - [ ] The URL canonicalisation does not seem to take place. For example when going to https://www.originprotocol.com/?lang_code=nl I don't get redirected to https://www.originprotocol.com/

**Comment by franckc** [comment]
@rolandpo The PR is deployed to production but it does not look like everything is fixed so I'm re-opening this issue.
 - [ ] When fetching the homepage at https://www.originprotocol.com, the server does not include the  `x-frame-options: DENY` header in the response
 - [ ] The URL canonicalisation does not seem to take place. For example when going to https://www.originprotocol.com/?lang_code=nl I don't get redirected to https://www.originprotocol.com/

**Comment by franckc** [comment]
@rolandpo The PR is deployed to production but it does not look like everything is fixed so I'm re-opening this issue.
 - [ ] When fetching the homepage at https://www.originprotocol.com, the server does not include the  `x-frame-options: DENY` header in the response
 - [ ] The URL canonicalisation does not seem to take place. For example when going to https://www.originprotocol.com/?lang_code=nl I don't get redirected to https://www.originprotocol.com/

**Comment by rolandpo** [comment]
right, the headers seemed to skip over the index page so #79 should fix that. The previous PR added a canonical url field to the seo to prevent duplicate indexing, but didn't add a redirect. I'll try and think about how to implement that if it's needed

**Comment by rolandpo** [comment]
pending #91

**Comment by franckc** [comment]
@rolandpo Can we close this issue or is there anything left to do?

**Comment by rolandpo** [comment]
I think so yeah
