### ISSUE TITLE
Web analytics: Implement GA4 + GTM

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#75]
See @jonathansnow 's doc: https://docs.google.com/document/d/1ctpM8JOzVYAS9IE_UlvpQOzSoqoZxjNTTUUwp_54Sic/edit#heading=h.cthb77etm5a0

We should implement GA4 + GTM across all our marketing sites:
 - [x] story.xyz
 - [x] originprotocol.com
 - [x] ousd.com

Let's also add GTM to the ousd subdomains:
 - [x] app.ousd.com
 - [x] analytics.ousd.com
 - [x] governance.ousd.com

**Comment by franckc** [comment]
I chatted with @jonathansnow about this. He made a great point that it would make sense to first implement on story.xyz since this could be the safest way to test out GA4+GTM given that we don't have any data for that site (vs ousd.com and op.com where we'll want to be a bit more careful to not lose the historical data). I have updated the ordering in the issue description above to reflect this.

**Comment by rolandpo** [comment]
some code set up in https://github.com/OriginProtocol/story.xyz/pull/7

**Comment by jonathansnow** [comment]
@rolandpo I quickly skimmed this. It looks like we're setting up both GTM and GA within _app.tsx?

We should be able to implement the GA code within the GTM container, so I don't think we'll need GA loaded directly. The dev guides linked in gtag.js are also for UA, which may differ from GA4. The pageview should be passed to the dataLayer (part of GTM), which allows us to trigger tags, like GA4, within GTM.

**Comment by rolandpo** [comment]
I removed the GA part of the code, will the triggers be able to be configured from just the GTM UI after that?

**Comment by jonathansnow** [comment]
It should be, as long as we have the pageview firing properly and passing it into the DataLayer. We will trigger tags based on these events, but the pageview will need to come from the site.

Why don't we try the way Vercel suggests (not too far off what we have now), then I can start to test within the GTM UI?
https://github.com/vercel/next.js/tree/canary/examples/with-google-tag-manager

Lines 20-23 are also GA import code, 36-48 were setup GA code.

**Comment by rolandpo** [comment]
ah got it thanks, updated
 will need @nickick or @franckc to look at deploying and updating the tracking ID on prod

**Comment by jonathansnow** [comment]
**GTM ID**: GTM-NSH9FWL

**Comment by franckc** [comment]
NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID has been set to the value above in prod. And the code was deployed as well.

Is there any work remaining or can we close this ticket?

**Comment by jonathansnow** [comment]
@franckc, should we leave it open until this is deployed on ousd.com, originprotocol.com, and relevant subdomains? Alternatively, we could edit this ticket to be story only and set up new tickets for the other properties?

Spot checks look fine for story.xyz. We are safe to get this deployed to the other two main sites and then we should do an inventory of all other sites set up on subdomains (staking, etc.) and figure out the deployment path for those as well.

**Comment by franckc** [comment]
Ah yes, let's use the same tickets for the other properties, at least for ousd.com and op.com - good call!

**Comment by franckc** [comment]
@rolandpo What's the latest on app.ousd.com and analytics.ousd.com - is GTM enabled on those 2 sites?

**Comment by rolandpo** [comment]
dapp PR is over here, not yet merged: https://github.com/OriginProtocol/origin-dollar. I'll look into analytics next

**Comment by rolandpo** [comment]
analytics pr here as a starting point https://github.com/OriginProtocol/ousd-analytics/pull/267

**Comment by jonathansnow** [comment]
I ran tests on all of our properties, and this is what's outstanding:
**governance.ousd.com** - DONE (February 6)
**analytics.ousd.com** - DONE (February 8)
**app.ousd.com** - BUG (duplicate pageview, legacy analytics conflict)
_Updated: February 9, 2023_

**Comment by franckc** [comment]
@jonathansnow Could you check if app.ousd.com is fixed or does it still need work? Thanks! :)

**Comment by jonathansnow** [comment]
@franckc I will sync up with Roland on this. We need to retire a bit more legacy code, and this issue will be wrapped up.
