### ISSUE TITLE
Page flickering

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/website-frontend#8]
When I first get to any page on the site, there is some flickering. Like the raw content shows up but not properly formatted/styled. Then after like a half second the styling/formatting gets applied.

@nickick mentioned: "The loading flicker is probably related to how the storybook components are being rendered serverside"

@shahthepro mentioned: "The flickering could also be because the stylesheets are loaded a bit late while the DOM structure is already in place (due to SSR)"

**Comment by nickick** [comment]
Completed this with db47daff197076a675f2a317129dd6e8c28a0884
