### ISSUE TITLE
/blog link has empty article pages

### ISSUE THREAD

**Issue by nickick** [OriginProtocol/website-frontend#93]
If you go to /blog, and hit page 4, nothing shows up.

![Screenshot 2023-01-30 at 2 29 56 PM](https://user-images.githubusercontent.com/1316662/215576541-13349919-7c8f-46c1-9751-6fbb2751d632.png)

**Comment by rolandpo** [comment]
was done in 089d0ad4fa48ed7a15fe1b5fb25fe1702ed0c1e8, needed a deploy
